name: GitHub metrics
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: "master"
  workflow_dispatch:
jobs:

  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, julia
          plugin_languages_skipped: wuwe1
          config_timezone: Asia/ShangHai
          
      - name: Personal metrics (additional)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "metadata"
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 3
